### ISSUE TITLE
Codec trouble in Anaconda

### ISSUE THREAD

**Issue by JosedeKruif** [maria-antoniak/goodreads-scraper#11]
Hi, 
When using Jupyter within Anaconda Encode errors occur. Error message:
raceback (most recent call last):
  File "get_books.py", line 205, in <module>
    main()
  File "get_books.py", line 200, in main
    print(str(datetime.now()) + ' ' + script_name + f':\n\n\U0001f389 Success! All book metadata scraped. \U0001f389\n\nMetadata files have been output to /{args.output_directory_path}\nGoodreads scraping run time = \u23f0 ' + str(datetime.now() - start_time) + ' \u23f0')
  File "C:\Users\famvanPolanenPetel\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f389' in position 44: character maps to <undefined>

**Comment by maria-antoniak** [comment]
We don't recommend running these scripts in Jupyter. Please try running at the command line instead.
