### ISSUE TITLE
Reviews script not working on titles with less than 10 pages of reviews

### ISSUE THREAD

**Issue by jenrhill** [maria-antoniak/goodreads-scraper#28]
Hi there. I'm running the reviews script and any time it reaches a title that has less than 10 pages of reviews (example page: https://www.goodreads.com/book/show/35725099-a-sister-in-my-house) the code stops. It'll scrape the pages that are available but it never generates the json file, nor does it  move on to the next title in the list. It basically freezes. The only way I can get it the code to work again is to remove the title from the list and start over without it included. Any ideas what's up? Thanks!

**Comment by maria-antoniak** [comment]
Hmm that's weird! Have you tried this with multiple books that have fewer than 10 pages of reviews? Could you list some of these book IDs?

**Comment by jenrhill** [comment]
Yes, I've tried multiple ones. Here are a few of them and all of these have less than 10 pages of reviews:
35725099-a-sister-in-my-house
30000138-forgotten-women
39331456-the-last-hour
43261143-the-tunnel
37578115-spies-of-no-country
53401989-the-memory-monster
31451164-this-is-not-a-border
2886972-if-all-the-seas-were-ink

**Comment by maria-antoniak** [comment]
I believe this issue has been resolved by #29. Sorry for the slow response, but let me know if you're still having issues!
