### ISSUE TITLE
[enhancement] Support filtering reviews by rating

### ISSUE THREAD

**Issue by purpleladydragons** [maria-antoniak/goodreads-scraper#32]
Hi, thank you for creating this repo! I recently used it to scrape some reviews, and I noticed that I could filter by rating in order to gather more reviews than the 300 limit. 

I've submitted a PR already since the diff was pretty small, but wanted to also file an issue to adhere to typical process. Happy to discuss any concerns here or in the [PR](https://github.com/maria-antoniak/goodreads-scraper/pull/31)

**Comment by maria-antoniak** [comment]
This looks great! Thanks so much for adding this; I've merged the PR and think it will be a very helpful addition!
