### ISSUE TITLE
HTTP Error 302

### ISSUE THREAD

**Issue by manzanacc** [maria-antoniak/goodreads-scraper#38]
While I am trying to scrap  the information about books (i.e., book ID and title, book ID, book title, ISBN), I got the following error: 

HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Found

I suppose that this error is due to the long book list that I have in txt format (70,000 books). Would you suggestion any solutions?

Thank you very much in advance!

**Comment by maria-antoniak** [comment]
Hmm I haven't seen that error before, and the long book list shouldn't matter. But the Goodreads site recently redesigned the book pages, so I wouldn't be surprised if that's the reason.
